/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CalendarCurrentDate: typeof import('./src/components/FullCalendar/trriger/CalendarCurrentDate.vue')['default']
    CalendarDayView: typeof import('./src/components/FullCalendar/views/CalendarDayView.vue')['default']
    CalendarHeader: typeof import('./src/components/FullCalendar/utils/CalendarHeader.vue')['default']
    CalendarMonthView: typeof import('./src/components/FullCalendar/views/CalendarMonthView.vue')['default']
    CalendarNextTrigger: typeof import('./src/components/FullCalendar/trriger/CalendarNextTrigger.vue')['default']
    CalendarPrevTrigger: typeof import('./src/components/FullCalendar/trriger/CalendarPrevTrigger.vue')['default']
    CalendarTodayTrigger: typeof import('./src/components/FullCalendar/trriger/CalendarTodayTrigger.vue')['default']
    CalendarViewTrigger: typeof import('./src/components/FullCalendar/trriger/CalendarViewTrigger.vue')['default']
    CalendarWeekView: typeof import('./src/components/FullCalendar/views/CalendarWeekView.vue')['default']
    CalendarYearView: typeof import('./src/components/FullCalendar/views/CalendarYearView.vue')['default']
    computed: typeof import('vue')['computed']
    defineComponent: typeof import('vue')['defineComponent']
    EventGroup: typeof import('./src/components/FullCalendar/utils/EventGroup.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NavigationMenu: typeof import('./src/components/ui/navigation-menu/NavigationMenu.vue')['default']
    NavigationMenuContent: typeof import('./src/components/ui/navigation-menu/NavigationMenuContent.vue')['default']
    NavigationMenuIndicator: typeof import('./src/components/ui/navigation-menu/NavigationMenuIndicator.vue')['default']
    NavigationMenuItem: typeof import('./src/components/ui/navigation-menu/NavigationMenuItem.vue')['default']
    NavigationMenuLink: typeof import('./src/components/ui/navigation-menu/NavigationMenuLink.vue')['default']
    NavigationMenuList: typeof import('./src/components/ui/navigation-menu/NavigationMenuList.vue')['default']
    NavigationMenuTrigger: typeof import('./src/components/ui/navigation-menu/NavigationMenuTrigger.vue')['default']
    NavigationMenuViewport: typeof import('./src/components/ui/navigation-menu/NavigationMenuViewport.vue')['default']
    onBeforeMount: typeof import('vue')['onBeforeMount']
    onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
    onMounted: typeof import('vue')['onMounted']
    onUnmounted: typeof import('vue')['onUnmounted']
    reactive: typeof import('vue')['reactive']
    ref: typeof import('vue')['ref']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TimeTable: typeof import('./src/components/FullCalendar/TimeTable.vue')['default']
    watch: typeof import('vue')['watch']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
